### ISSUE TITLE
visual c++ compilation OT::OTROBOPT::OTRobOptResourceMap_init and pthread. Dead code ?

### ISSUE THREAD

**Issue by nitawa** [openturns/otrobopt#40]
Dear developers,
(editing)

I am trying to compile otrobopt on **windows** and experience an issue with one class `OT::OTROBOPT::OTRobOptResourceMap_init`
This class implemented in  `MeasureEvaluation.cxx ` source file which  does not compile because of pthreads dependency which was obviously removed in version 1.21 of Openturns but was present in sources of Openturns 1.20.

Do you know which version of  pthreads I need to use to get it compiled, since in version 1.20 pthreads was shipped in openturns, but it seems to have been removed in version 1.21.

Thanks for your valuable feeback.

**Comment by nitawa** [comment]
updating my question (had an issue with the grepwin tool...)

**Comment by jschueller** [comment]
our code is incorrect, we need to use std::mutex now

**Comment by nitawa** [comment]
do you have a patch by chance, that I can apply here?
thanks

**Comment by jschueller** [comment]
see #41
